### ISSUE TITLE
Download links on main website giving 404

### ISSUE THREAD

**Issue by mandy-chessell** [cloudinformationmodel/cloudinformationmodel#14]
On webpage https://cloudinformationmodel.org/cim-formats/
there are a series of download links to retrieve the model contents in different formats.
The links are currently giving a 404.

**Comment by jpradocueva** [comment]
Thanks for let us know. I will look into that and report back here, it was working before.

**Comment by jpradocueva** [comment]
@mandy-chessell problem has been solved.
